config/routes.rb
Rails.application.routes.draw do

  resources :calls
  resources :reports
  resources :pickups
  resources :routes
  resources :routes_and_checkpoints_linkers
  resources :checkpoint_times
  resources :brandings
  resources :events do
    post :make_public, on: :collection
    post :make_private, on: :collection
  end
  resources :checkpoints do
    get 'from_file', on: :collection
    post :upload_excel, on: :collection
  end
  #resources :participants
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    get 'pick_route', on: :collection
    post :route_picked, on: :collection
  end
 
  resources :pages do 
    get 'home', on: :member
    get 'pick_event', on: :collection
    get 'pick_route', on: :member
    get 'leaderboard', on: :collection
    get 'single_user_leaderboard', on: :collection
  end

  resources :walkers do
    get 'check_in', on: :collection
    get 'requestCall'
    get 'requestPickUp'
    get 'check_in_fail', on: :collection
    get 'checkpoint_info', on: :collection
    get 'help', on: :collection
    get 'drop_out', on: :collection
    get 'search', on: :collection
    post 'saveLocation'
    get 'sign_up_participant'
    post :make_own_way_home, on: :collection
  end

  resources :admins do
    get 'pick_route', on: :collection
    get 'view_marshals', on: :collection
    get 'view_walkers', on: :collection
    get 'view_pickups', on: :collection
    get 'walkers_profile', on: :collection
    get 'view_calls', on: :collection
    post :make_walker_marshal, on: :collection
    post :make_user_admin, on: :collection
    post :choose_a_route, on: :collection
    get 'checkpoint_order', on: :collection
    get 'view_reports', on: :collection
    post :route_picked, on: :collection
  end

  resources :marshals do
    get 'choose_event', on: :collection
    get 'add_shift', on: :member
    get 'view_incoming_walkers', on: :collection
    get 'change_checkpoint', on: :collection
    post :search_checkpoint, on: :collection
    get 'end_marshal_shift', on: :collection
    get 'end_for_the_day', on: :collection
    get 'checkin_walkers', on: :collection
    post :checkin_walker, on: :collection
    
    get 'move_own_way_home', on: :collection
    get 'request_pick_up', on: :collection
    get 'pause_marshalling', on: :collection
    get 'resume_marshalling', on: :collection
    
    end

  resources :profile do
    get 'account', on: :collection
  end
  
  mount EpiCas::Engine, at: "/"
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get '/marshals/:id', to: 'marshals#index'
  get '/walkers/:id', to: 'walkers#index'


  root :to => redirect("/users/sign_in")
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/walkers_controller.rb
class WalkersController < ApplicationController
  before_action :authenticate_user!
  before_action do
    # Check role
    user = User.where(id: session[:current_user_id]).first
    tag = Tag.where(id: user.tag_id).first
    if tag.name == "Walker"
    elsif tag.name == "Marshal"
      redirect_to pick_event_pages_path, notice: 'You dont have access to that page'
    elsif tag.name == "Admin"
      redirect_to events_path, notice: 'You dont have access to that page'
    end
  end

  def check_in
    #find next checkpoint
    user = User.where(id: session[:current_user_id]).first
    walker = Participant.where(user_id: user.id).first
    checkpoint_pos = RoutesAndCheckpointsLinker.where(route_id: walker.routes_id, checkpoint_id: walker.checkpoints_id).first.position_in_route
    @linker = RoutesAndCheckpointsLinker.where(position_in_route: (checkpoint_pos + 1), route_id: walker.routes_id).first
    @checkpoint = Checkpoint.where(id: @linker.checkpoint_id).first

    # Compare current location with checkpoint location
    if session[:osReference] == @checkpoint.os_grid
      walker.update(pace: "On Pace.")
      walker.update(checkpoints_id: @checkpoint.id)
      #create checkpoint time for walker
      time = Time.now
      checkpoint_time = CheckpointTime.new
      checkpoint_time.times = time 
      checkpoint_time.checkpoint_id = @checkpoint.id
      checkpoint_time.participant_id = walker.id
      checkpoint_time.save
      #rerank the walker
      #gets walkers at that checkpoint same on route 
      walkers_on_route = Participant.where(routes_id: walker.routes_id, checkpoints_id: @checkpoint.id)

      lowest_rank = 0
      #checks whos gone past that checkpoint with lowest rank 
      walkers_on_route.each do |walkers|
        if walkers.rank > lowest_rank && walkers.rank != walker.rank
          lowest_rank = walkers.rank
        end
      end
      old_rank = walker.rank.dup
      #if rank is the same dont update
      #if noone has then they are in 1st
      if (lowest_rank + 1) != walker.rank
        walker.update(rank: (lowest_rank + 1))
      end

      #reranks rest
      #old rank and new rank everyone inbetween gets shifted down if rank is increased
      if old_rank > (lowest_rank + 1)
        walkers_rerank = Participant.where(routes_id: walker.routes_id).where("rank < ?", old_rank).where("rank >= ?", (lowest_rank + 1))
        walkers_rerank.each do |walkers|
          if walkers.id != walker.id
            walkers.update(rank: (walkers.rank + 1))
          end
        end
      end

      user = User.where(id: walker.user_id).first
      route = Route.where(id: walker.routes_id).first
      checkpoint = Checkpoint.where(id: walker.checkpoints_id).first
      spreadsheet = Spreadsheet.new
      spreadsheet.update_walker_rank(route, old_rank, user)
      spreadsheet.add_checkpoint_time(route, user, checkpoint)
      redirect_to walker_path(session[:current_route_id]), notice: "Check In Succeffully"
    else
      redirect_to check_in_fail_walkers_path
    end
  end

  def saveLocation
    #get latitude and longitue 
    @lat = params[:lat].to_f
    @lon = params[:lon].to_f
    session[:lat] = @lat
    session[:lon] = @lon
    #conver them to OS Reference(Method 1)
    # @wgs84_point = OsgbConvert::WGS84.new(@lat, @lon, 0)
    # @osUKgridPoint = OsgbConvert::OSGrid.from_wgs84(@wgs84_point)
    # @osReference = @osUKgridPoint.grid_ref(6)

    #conver them to OS Reference(Method 2)
    osgb36point = OSGB_WGS84::WGS84_to_OSGB36(@lat,@lon, 0)
    oslat = osgb36point[0]
    oslon = osgb36point[1]
    osUKgridPoint = OSGB_WGS84::OSGB36_to_OSNG(oslat,oslon)
    easting  = osUKgridPoint[0].round
    northing = osUKgridPoint[1].round
    @osReference = OSGB_WGS84::OSNG_numbers_to_letters(easting,northing, 6)

    # Pass to session and redirect to home page
    session[:osReference] = @osReference
    redirect_to walker_path(session[:current_route_id]), notice:"Your location has been updated."
  end

  def sign_up_participant
    # Give Participant random participant_number
    random_number = 0
    (1000..1999).each do |id| 
      walker_ids = Participant.where(participant_id: id).first
      if !walker_ids
        random_number = id
        break
      end
    end
    #Update checkpoint
    checkpoint_id = RoutesAndCheckpointsLinker.where(route_id: session[:current_route_id], position_in_route: "1").first.checkpoint_id
    participant = Participant.where(routes_id:session[:current_route_id], user_id:session[:current_user_id]).first_or_create(participant_id: random_number, checkpoints_id:checkpoint_id, routes_id: session[:current_route_id], user_id: session[:current_user_id], event_id: session[:current_event_id], rank: (Participant.where(routes_id:session[:current_route_id]).size + 1), pace: "On Pace.")#, opted_in_leaderboard: session[:opted_in])
    participant.save
    route = Route.where(id: session[:current_route_id]).first
    user =  User.where(id:session[:current_user_id]).first
    start_date = route.start_date
    start_time = route.start_time
    date_time = DateTime.new(start_date.year, start_date.month, start_date.day, start_time.hour, start_time.min, start_time.sec, start_time.zone)
    CheckpointTime.where(participant_id: participant.id, checkpoint_id: checkpoint_id).first_or_create(times: date_time, participant_id: participant.id, checkpoint_id: checkpoint_id)
    spreadsheet = Spreadsheet.new
    spreadsheet.add_walker(route, user)

    
    if participant.save
      redirect_to walker_path(session[:current_route_id])
    else
      redirect_to home_page_path(session[:current_event_id]), notice: 'You dont have access to that page.'
    end

  end


  def requestCall
    #Create a call record
    Call.create(user_id:current_user.id, event_id:session[:current_event_id])
    redirect_to help_walkers_path, notice: 'Call request successful.'
  end

  def requestPickUp
    #Create a pick up record
    route = Route.where(id: session[:current_route_id]).first
    user = User.where(id: session[:current_user_id]).first
    Pickup.create(user_id:current_user.id, event_id:session[:current_event_id], os_grid: session[:osReference])
    spreadsheet = Spreadsheet.new
    spreadsheet.walker_pickup(route, user)
    redirect_to help_walkers_path, notice: 'Pick up request successful.'
  end


  def check_in_fail
    # If location not match, redirect to this page
    user = User.where(id: session[:current_user_id]).first
    walker = Participant.where(user_id: user.id).first
    checkpoint_pos = RoutesAndCheckpointsLinker.where(route_id: walker.routes_id, checkpoint_id: walker.checkpoints_id).first.position_in_route
    @linker = RoutesAndCheckpointsLinker.where(position_in_route: (checkpoint_pos + 1), route_id: walker.routes_id).first
    @checkpoint = Checkpoint.where(id: @linker.checkpoint_id).first

    @lat = session[:lat].to_f
    @lon = session[:lon].to_f
    @osReference = session[:osReference]
  end

  def help
    @findEvent = Event.where(id: session[:current_event_id]).first
    @head_marshal_num = @findEvent.phone_number
  end

  def drop_out
  end
  
  def make_own_way_home
    walker = Participant.where(user_id: session[:current_user_id], routes_id: session[:current_route_id]).first
    route = Route.where(id: session[:current_route_id]).first
    user = User.where(id: walker.user_id).first
    spreadsheet = Spreadsheet.new
    spreadsheet.walker_drop_out(route, user)
    #times = CheckpointTime.where(participant_id: walker.id)
    #times.each do |time|
    #  time.destroy
    #end
    walker.destroy
    reset_session
    redirect_to '/'
  end


  def checkpoint_info
    user = User.where(id: session[:current_user_id]).first
    walker = Participant.where(user_id: user.id).first
    checkpoint_pos = RoutesAndCheckpointsLinker.where(route_id: walker.routes_id, checkpoint_id: walker.checkpoints_id).first.position_in_route
    @linker = RoutesAndCheckpointsLinker.where(position_in_route: (checkpoint_pos + 1), route_id: walker.routes_id).first
    @checkpoint = Checkpoint.where(id: @linker.checkpoint_id).first
  end
  
  def search
    @search = User.ransack(params[:q])
    @users = @search.result(distinct: true)
  end

  def inbox
  end

  def index
    
  end

  def show
    ####
    #puts "656565 #{params[:id]}"
    #params_id = params[:id]
    #session[:current_route_id] = params_id[:route_id]

    
    #####
    user = User.where(id: session[:current_user_id]).first
    
    @walker = Participant.where(user_id: user.id, routes_id: params[:id]).first
    
    
    checkpoint_pos = RoutesAndCheckpointsLinker.where(route_id: @walker.routes_id, checkpoint_id: @walker.checkpoints_id).first.position_in_route
    if checkpoint_pos == RoutesAndCheckpointsLinker.where(route_id: @walker.routes_id).size
      
    else
      @linker = RoutesAndCheckpointsLinker.where(position_in_route: (checkpoint_pos ), route_id: @walker.routes_id).first
      @checkpoint = Checkpoint.where(id: @linker.checkpoint_id).first
      #what happens when they finish
      @advisedTime = @linker.advised_time
      checkpoint_time = CheckpointTime.where(checkpoint_id: @walker.checkpoints_id, participant_id: @walker.id).first
      if checkpoint_time
        @time = checkpoint_time.times
      else
        #@time = DateTime.new()
        #event starts
        route = Route.where(id: @walker.routes_id).first
        start_time = route.start_time
        start_date = route.start_date
        @time = DateTime.new(start_date.year, start_date.month, start_date.day, start_time.hour, start_time.min, start_time.sec, start_time.zone)
      end
    end
  end
  
  private 
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @user = User.find(params[:id])
  end

  def report_params
    params.permit(:subject, :description)
  end
end

app/views/walkers/drop_out.html.haml
.d-flex.justify-content-center
    %h1{class: "fw-bold"} Dropping Out
%br/
.d-flex.justify-content-center
    %h5 We're sorry to see you go!
%br/
.d-flex.justify-content-center
    %p{class: "text-center"} Well done on all your hard work today. Now you're finishing up, do you need picking up, or are you making your own way home?
%br/
.d-grid.gap-2
    = simple_form_for :make_own_way_home, url: make_own_way_home_walkers_path, method: :post do |f|
        = f.submit "Making My Own Way Home", class: 'btn btn-primary primary-button w-100'
    =link_to "I Need Picking Up", walker_requestPickUp_path(current_user), class: 'btn btn-primary primary-button'

app/views/walkers/help.html.haml
.d-flex.justify-content-center
    %h1.fw-bold How Can We Help?
%br/

.d-grid.gap-2
    %a.btn.btn-primary.primary-button.btn-lg(href="/walkers/#{current_user.id}/requestCall") Request Call From Staff
    %a.btn.btn-primary.primary-button.btn-lg(href="tel:[#{@head_marshal_num}]") Call Head Marshall (Emergency)
    =link_to "I'd Like To Drop Out", drop_out_walkers_path, class: 'btn btn-primary primary-button btn-lg'
    =link_to "Report Issue With The Website", new_report_path, class: 'btn btn-primary primary-button btn-lg'

app/views/walkers/index.html.haml
%br
.row 
    .col
        -if @linker
            .d-flex.justify-content-center
                %h1{class: "fw-bold"} LET'S GO! 
            .d-flex.justify-content-center
                %h2{class: "fw-bold"} The event has begun! 
            %br
            .d-flex.justify-content-center
                %h4{class: "fw-bold"} You are currently
            -if @walker.rank % 10 == 0 || @walker.rank % 10 == 4 || @walker.rank % 10 == 5 || @walker.rank % 10 == 6 || @walker.rank % 10 == 7 || @walker.rank % 10 == 8 || @walker.rank % 10 == 9
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}th"
            -elsif @walker.rank % 10 == 1
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}st"
            -elsif @walker.rank % 10 == 2
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}nd"
            -elsif @walker.rank % 10 == 3
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}rd"

            %br
            .d-flex.justify-content-center
                %h4.fw-bold Your next checkpoint:
            .d-flex.justify-content-center
                %h1.fw-bold.text-center.text-uppercase= @checkpoint.name
            %br
            .d-flex.justify-content-center
                %h4{:id => "countdownMsg", class: "fw-bold"}
            .d-flex.justify-content-center
                %h4{:id => "countdownMsg2", class: "fw-bold"}
            .d-flex.justify-content-center
                %h1{:id => "countdown", class: "fw-bold"} Countdown Loading...
            .d-flex.justify-content-center
                %h1{:id => "countdown2", class: "fw-bold"} Countdown Loading...
            .d-flex.justify-content-center
                %h1{:id => "countdown3", class: "fw-bold"} Countdown Loading...
            %h4{:id => "rubyCode", class: "fw-bold"}
                /current time c
                /time reached last checkpoint l
                /c - l = time since last checkpoint s
                /adviced time a - s = time left to reach next checkpoint n
                /if n < 0 set status to falling behind and timer starts to increase 
                :javascript
                    var checkpointTimeDate = new Date("#{@time}").getTime();
                    var x = setInterval(function() {
                        var now = new Date().getTime();
                        //var now = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), date.getUTCHours(), date.getUTCMinutes(), date.getUTCSeconds());
                        //var timeFromLast = now - (checkpointTimeDate - 3600000);
                        var timeFromLast = now - checkpointTimeDate;
                        document.getElementById("countdown2").innerHTML = new Date("#{@time}");
                        document.getElementById("countdown3").innerHTML = now;
                        var timeLeftToReach = (parseInt("#{@advisedTime}") * 60000) - timeFromLast;
                        var days = Math.floor(timeFromLast / (1000 * 60 * 60 * 24));
                        var hours = Math.floor((timeFromLast % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                        var minutes = Math.floor((timeLeftToReach % (1000 * 60 * 60)) / (1000 * 60));
                        var seconds = Math.floor((timeLeftToReach % (1000 * 60)) / 1000);
                        document.getElementById("countdownMsg").innerHTML = "You are expected to reach";
                        document.getElementById("countdownMsg2").innerHTML = "the next checkpoint within:";
                        if (timeLeftToReach < 0) {
                            document.getElementById("countdownMsg").innerHTML = "You are";
                            document.getElementById("countdownMsg2").innerHTML = "running late by:";
                            days = days 
                            hours = hours
                            minutes = - minutes - 1
                            seconds = - seconds
                            //document.getElementById("rubyCode").innerHTML = '#{@walker.update(status: "Falling Behind!")}';
                            var a = '#{@walker.update(status: "Falling Behind!")}';

                        } else {
                            var a = '#{@walker.update(status: "On Pace.")}';
                        }
                        if (days > 0){
                            document.getElementById("countdown").innerHTML = days + "D : " + hours + "H : " + minutes + "M : " + seconds + "S ";
                        } else if ((days <= 0) && (hours > 0)){
                            document.getElementById("countdown").innerHTML = hours + "H : " + minutes + "M : " + seconds + "S ";
                        } else if ((days <= 0) && (hours <= 0) && (minutes > 0)){
                            document.getElementById("countdown").innerHTML = minutes + "M : " + seconds + "S ";
                        } else if ((days <= 0) && (hours <= 0) && (minutes <= 0) && (seconds > 0)){
                            document.getElementById("countdown").innerHTML = seconds + "S ";
                        } else {
                            document.getElementById("countdown").innerHTML = "countdown is broken";
                        }
                        
                    }, 1000);
        -else
            .d-flex.justify-content-center
                %h1 Congratulations
            .d-flex.justify-content-center
                %h2 You Finished The Event
        %br/
        %br/


.d-grid.gap-2
    .d-flex.justify-content-center
        .p#out
    = render"getLatLong"
    -# =link_to "Check In", check_in_walkers_path, class: 'btn btn-primary primary-button'
    -# =link_to "Check In Failed", check_in_fail_walkers_path, class: 'btn btn-primary primary-button'
    =link_to "Check Point Information", checkpoint_info_walkers_path, class: 'btn btn-primary primary-button'
    =link_to "Leaderboard", leaderboard_pages_path, class: 'btn btn-primary primary-button'
    =link_to "View My Times", single_user_leaderboard_pages_path(:leaderboard_participant_id => session[:current_user_id]), class: 'btn btn-primary primary-button'
    =link_to "Request Help", help_walkers_path, class: 'btn btn-primary primary-button'


:javascript
    geoFindMe()
    function geoFindMe() {
    var output = document.getElementById("out");
    var latitude;
    var longitude;

    function success(position) {
        latitude  = position.coords.latitude.toFixed(6);
        longitude = position.coords.longitude.toFixed(6);

        lat = document.getElementById("lat");
        lon = document.getElementById("lon");
        lat.value = latitude;
        lon.value = longitude;

        output.innerHTML = '<p>Latitude is ' + latitude + '° <br>Longitude is ' + longitude + '°</p>';
        // window.initMap = initMap();

    };

    function error() {
        output.innerHTML = "Unable to find position.";
    };
    output.innerHTML = "<p>Finding Your Current Location…</p>";
    navigator.geolocation.getCurrentPosition(success, error);
    }

app/views/walkers/show.html.haml
.row 
    .col
        -if @linker
            .d-flex.justify-content-center
                %h1{class: "fw-bold"} LET'S GO! 
            .d-flex.justify-content-center
                %h2{class: "fw-bold"} The event has begun! 
            %br
            .d-flex.justify-content-center
                %h4{class: "fw-bold"} You are currently
            -if @walker.rank % 10 == 0 || @walker.rank % 10 == 4 || @walker.rank % 10 == 5 || @walker.rank % 10 == 6 || @walker.rank % 10 == 7 || @walker.rank % 10 == 8 || @walker.rank % 10 == 9
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}th!"
            -elsif @walker.rank % 10 == 1
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}st!"
            -elsif @walker.rank % 10 == 2
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}nd!"
            -elsif @walker.rank % 10 == 3
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}rd!"

            %br
            .d-flex.justify-content-center
                %h4.fw-bold Your next checkpoint:
            .d-flex.justify-content-center
                %h1.fw-bold.text-center.text-uppercase= @checkpoint.name
            %br
            .d-flex.justify-content-center
                %h4{:id => "countdownMsg", class: "fw-bold"}
            .d-flex.justify-content-center
                %h4{:id => "countdownMsg2", class: "fw-bold"}
            .d-flex.justify-content-center
                %h1{:id => "countdown", class: "fw-bold"} Countdown Loading...
                /current time c
                /time reached last checkpoint l
                /c - l = time since last checkpoint s
                /adviced time a - s = time left to reach next checkpoint n
                /if n < 0 set status to falling behind and timer starts to increase 
                :javascript
                    var checkpointTimeDateArr = "#{@time}".split(/[- :]/);
                    var checkpointTimeDates = new Date(checkpointTimeDateArr[0], checkpointTimeDateArr[1]-1, checkpointTimeDateArr[2], parseInt(checkpointTimeDateArr[3])+2, checkpointTimeDateArr[4], checkpointTimeDateArr[5]);
                    var checkpointTimeDate = new Date(checkpointTimeDates.getUTCFullYear(), checkpointTimeDates.getUTCMonth(), checkpointTimeDates.getUTCDate(), checkpointTimeDates.getUTCHours(), checkpointTimeDates.getUTCMinutes(), checkpointTimeDates.getUTCSeconds()).getTime();
                    var x = setInterval(function() {
                        var date = new Date();
                        var now = new Date(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), date.getUTCHours(), date.getUTCMinutes(), date.getUTCSeconds()).getTime();
                        var timeFromLast = now - (checkpointTimeDate - 3600000);
                        var timeLeftToReach = (parseInt("#{@advisedTime}") * 60000) - timeFromLast;
                        var days = Math.floor(timeLeftToReach / (1000 * 60 * 60 * 24));
                        var hours = Math.floor((timeLeftToReach % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                        var minutes = Math.floor((timeLeftToReach % (1000 * 60 * 60)) / (1000 * 60));
                        var seconds = Math.floor((timeLeftToReach % (1000 * 60)) / 1000);
                        document.getElementById("countdownMsg").innerHTML = "You are expected to reach the";
                        document.getElementById("countdownMsg2").innerHTML = "next checkpoint within:";
                        if (timeLeftToReach < 0) {
                            document.getElementById("countdownMsg").innerHTML = "You are running late by:"
                            document.getElementById("countdownMsg2").innerHTML = ""
                            days = - days - 1
                            hours = - hours - 1
                            minutes = - minutes - 1
                            seconds = - seconds
                        }
                        if (days > 0){
                            document.getElementById("countdown").innerHTML = days + "D : " + hours + "H : " + minutes + "M : " + seconds + "S ";
                        } else if ((days <= 0) && (hours > 0)){
                            document.getElementById("countdown").innerHTML = hours + "H : " + minutes + "M : " + seconds + "S ";
                        } else if ((days <= 0) && (hours <= 0) && (minutes > 0)){
                            document.getElementById("countdown").innerHTML = minutes + "M : " + seconds + "S ";
                        } else if ((days <= 0) && (hours <= 0) && (minutes <= 0) && (seconds > 0)){
                            document.getElementById("countdown").innerHTML = seconds + "S ";
                        } else {
                            document.getElementById("countdown").innerHTML = "Failed to load countdown.";
                        }
                        
                    }, 1000);
        -else
            .d-flex.justify-content-center
                %h1 Congratulations
            .d-flex.justify-content-center
                %h2 You Finished The Event
            %br
            .d-flex.justify-content-center
                %h4{class: "fw-bold"} You are currently
            -if @walker.rank % 10 == 0 || @walker.rank % 10 == 4 || @walker.rank % 10 == 5 || @walker.rank % 10 == 6 || @walker.rank % 10 == 7 || @walker.rank % 10 == 8 || @walker.rank % 10 == 9
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}th"
            -elsif @walker.rank % 10 == 1
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}st"
            -elsif @walker.rank % 10 == 2
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}nd"
            -elsif @walker.rank % 10 == 3
                .d-flex.justify-content-center
                    %h1{class: "fw-bold"}= "#{@walker.rank}rd"




.d-grid.gap-2
    .d-flex.justify-content-center
    = render"getLatLong"
    =link_to "Check Me In", check_in_walkers_path, class: 'btn btn-primary primary-button'
    -# =link_to "Check In Failed", check_in_fail_walkers_path, class: 'btn btn-primary primary-button'
    =link_to "Check Point Information", checkpoint_info_walkers_path, class: 'btn btn-primary primary-button'
    =link_to "Leaderboard", leaderboard_pages_path, class: 'btn btn-primary primary-button'
    =link_to "View My Times", single_user_leaderboard_pages_path(:leaderboard_user_id => session[:current_user_id]), class: 'btn btn-primary primary-button'
    =link_to "Request Help", help_walkers_path, class: 'btn btn-primary primary-button'
    %br
%br
    %table.table.table-hover.table-sm
        %thead
            %tbody
                %tr
                    %td.p#out
:javascript
    geoFindMe()
    function geoFindMe() {
    var output = document.getElementById("out");
    var latitude;
    var longitude;

    function success(position) {
        latitude  = position.coords.latitude.toFixed(6);
        longitude = position.coords.longitude.toFixed(6);

        lat = document.getElementById("lat");
        lon = document.getElementById("lon");
        lat.value = latitude;
        lon.value = longitude;
        output.innerHTML = '<p>Your Location Is Up To Date</p>';
        // output.innerHTML = '<p>Latitude is ' + latitude + '° <br>Longitude is ' + longitude + '°</p>';
        // window.initMap = initMap();

    };

    function error() {
        output.innerHTML = "Unable to find position.";
    };
    output.innerHTML = "<p>Requesting Access To Location...</p>";
    navigator.geolocation.getCurrentPosition(success, error);
    }