config/routes.rb
Rails.application.routes.draw do

  resources :calls
  resources :reports
  resources :pickups
  resources :routes
  resources :routes_and_checkpoints_linkers
  resources :checkpoint_times
  resources :brandings
  resources :events do
    post :make_public, on: :collection
    post :make_private, on: :collection
  end
  resources :checkpoints do
    get 'from_file', on: :collection
    post :upload_excel, on: :collection
  end
  #resources :participants
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    get 'pick_route', on: :collection
    post :route_picked, on: :collection
  end
 
  resources :pages do 
    get 'home', on: :member
    get 'pick_event', on: :collection
    get 'pick_route', on: :member
    get 'leaderboard', on: :collection
    get 'single_user_leaderboard', on: :collection
  end

  resources :walkers do
    get 'check_in', on: :collection
    get 'requestCall'
    get 'requestPickUp'
    get 'check_in_fail', on: :collection
    get 'checkpoint_info', on: :collection
    get 'help', on: :collection
    get 'drop_out', on: :collection
    get 'search', on: :collection
    post 'saveLocation'
    get 'sign_up_participant'
    post :make_own_way_home, on: :collection
  end

  resources :admins do
    get 'pick_route', on: :collection
    get 'view_marshals', on: :collection
    get 'view_walkers', on: :collection
    get 'view_pickups', on: :collection
    get 'walkers_profile', on: :collection
    get 'view_calls', on: :collection
    post :make_walker_marshal, on: :collection
    post :make_user_admin, on: :collection
    post :choose_a_route, on: :collection
    get 'checkpoint_order', on: :collection
    get 'view_reports', on: :collection
    post :route_picked, on: :collection
  end

  resources :marshals do
    get 'choose_event', on: :collection
    get 'add_shift', on: :member
    get 'view_incoming_walkers', on: :collection
    get 'change_checkpoint', on: :collection
    post :search_checkpoint, on: :collection
    get 'end_marshal_shift', on: :collection
    get 'end_for_the_day', on: :collection
    get 'checkin_walkers', on: :collection
    post :checkin_walker, on: :collection
    
    get 'move_own_way_home', on: :collection
    get 'request_pick_up', on: :collection
    get 'pause_marshalling', on: :collection
    get 'resume_marshalling', on: :collection
    
    end

  resources :profile do
    get 'account', on: :collection
  end
  
  mount EpiCas::Engine, at: "/"
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get '/marshals/:id', to: 'marshals#index'
  get '/walkers/:id', to: 'walkers#index'


  root :to => redirect("/users/sign_in")
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/checkpoint.rb
# == Schema Information
#
# Table name: checkpoints
#
#  id         :bigint           not null, primary key
#  name       :string
#  os_grid    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  event_id   :bigint           not null
#
# Indexes
#
#  index_checkpoints_on_event_id  (event_id)
#
# Foreign Keys
#
#  fk_rails_...  (event_id => events.id)
#
class Checkpoint < ApplicationRecord
    validates_presence_of :name
    validates :os_grid, presence: true, format: { with: /[A-Z]{2}\d{6}/ }
    validates_uniqueness_of :name, scope: :event_id

    belongs_to :event, class_name: "Event", foreign_key: "event_id"
    has_many :routes_and_checkpoints_linkers
    has_many :checkpoint_times
    has_many :participants
    has_many :marshalls
end

app/controllers/checkpoints_controller.rb
class CheckpointsController < ApplicationController
  before_action :set_checkpoint, :authenticate_user!, only: [:show, :edit, :update, :destroy]
  before_action do
    user = User.where(id: session[:current_user_id]).first
    tag = Tag.where(id: user.tag_id).first
    if tag.name == "Admin"
    elsif tag.name == "Marshal"
      redirect_to pick_event_pages_path, notice: 'You dont have access to that page'
    elsif tag.name == "Walker"
      redirect_to pick_event_pages_path, notice: 'You dont have access to that page'
    end
  end

  # GET /checkpoints
  def index
    @checkpoints = Checkpoint.where(event_id: session[:current_event_id])
    @branding = Branding.where(event_id: session[:current_event_id]).first
    @event = Event.where(id: session[:current_event_id]).first
  end

  # GET /checkpoints/1
  def show
    @checkpoints = Checkpoint.where(event_id: session[:current_event_id])
  end

  # GET /checkpoints/new
  def new
    @checkpoint = Checkpoint.new
    @linker = RoutesAndCheckpointsLinker.new
    #@routes = Route.where(event_id: session[:current_event_id])
  end

  # GET /checkpoints/1/edit
  def edit
    #@routes = Route.where(event_id: session[:current_event_id])
  end

  def upload_excel
    #unless params[:file].nil?
    file = (params.require(:upload_excel).permit(:file))[:file]
    spreadsheet = Spreadsheet.new
    route_ids = params[:selected_routes]
    route_ids.each do |id|
      route = Route.where(id: id).first
      spreadsheet.upload_event(file, route)
    end
    redirect_to checkpoints_path
    #end
  end

  # POST /checkpoints
  def create
    #creates the new checkpoint
    @checkpoint = Checkpoint.new(checkpoint_params)
    @checkpoint.event_id = session[:current_event_id]
    if @checkpoint.save 

      #gets the selected routes
      @route_ids = params[:selected_routes]
      session[:linker_route_ids] = @route_ids
      session[:linker_route_ids_index] = 0
      session[:linker_check_id] = @checkpoint.id
      new_linkers = Array.new

      #adds each to route with the checkpoint to the linker table
      if @route_ids
        @route_ids.each do |id|
          @linker = RoutesAndCheckpointsLinker.new
          @linker.checkpoint_id = @checkpoint.id

          #set dist from start and pos in route
          # linkers = RoutesAndCheckpointsLinker.where(route_id: id)
          # smallest_pos = 1
          # smallest_dist = 1
          # linkers.each do |linker|
          #   if linker.position_in_route < smallest_pos
          #     smallest_pos = linker.position_in_route
          #   end
          #   if linker.distance_from_start < smallest_dist
          #     smallest_dist = linker.distance_from_start
          #   end
          # end
          #@linker.distance_from_start = smallest_dist - 1
          linker = RoutesAndCheckpointsLinker.where(route_id: id).order("position_in_route DESC").first
          if linker
            @linker.distance_from_start = linker.distance_from_start + 1
            @linker.position_in_route = linker.position_in_route + 1
          else
            @linker.distance_from_start = 1
            @linker.position_in_route = 1
          end
          @linker.route_id = id
          #@linker.position_in_route = smallest_pos - 1
          @linker.advised_time = 0
          @linker.save
          new_linkers.push(@linker.id)
        end
        session[:new_linkers] = new_linkers

        #finds the next linker and redirects to it
        @route_id = session[:linker_route_ids].at(session[:linker_route_ids_index])
        @route = RoutesAndCheckpointsLinker.where(checkpoint_id: session[:linker_check_id], route_id: @route_id)
        
        @route.each do |route|
          redirect_to edit_routes_and_checkpoints_linker_path(route)
        end
      else
        redirect_to checkpoints_path
      end
    else
      render :new
    end
  end

  # PATCH/PUT /checkpoints/1
  def update
    spreadsheet = Spreadsheet.new
    old_checkpoint_name = @checkpoint.name.dup
    if @checkpoint.update(checkpoint_params)

      #get the selected routes
      @route_ids = params[:selected_routes]
      if @route_ids
        @route_ids.each do |id|
          if old_checkpoint_name != @checkpoint.name
            spreadsheet.update_checkpoint_name((Route.where(id: id).first), @checkpoint)
          end
        end
      end
      session[:linker_route_ids] = @route_ids
      session[:linker_route_ids_index] = 0
      session[:linker_check_id] = @checkpoint.id
      new_linkers = Array.new

      #check if the routes are already in the linker with the checkpoint
      @routes = Route.where(event_id: @checkpoint.event_id)
      @routes.each do |route|
        if RoutesAndCheckpointsLinker.exists?(checkpoint_id: session[:linker_check_id], route_id: route.id) && (!@route_ids || !(session[:linker_route_ids].include? (route.id).to_s))
          #delete from linker table
          @linker = RoutesAndCheckpointsLinker.where(checkpoint_id: session[:linker_check_id], route_id: route.id)
          @linker.each do |linker|
            spreadsheet.delete_checkpoint(route, old_checkpoint_name, linker.position_in_route)
            linker.destroy
          end
        elsif !RoutesAndCheckpointsLinker.exists?(checkpoint_id: session[:linker_check_id], route_id: route.id) && (@route_ids && (session[:linker_route_ids].include? (route.id).to_s)) 
          #add to linker table
          @linker = RoutesAndCheckpointsLinker.new
          @linker.checkpoint_id = @checkpoint.id

          #set dist from start and pos in route
          # linkers = RoutesAndCheckpointsLinker.where(route_id: route.id)
          # smallest_pos = 1
          # smallest_dist = 1
          # linkers.each do |linker|
          #   if linker.position_in_route < smallest_pos
          #     smallest_pos = linker.position_in_route
          #   end
          #   if linker.distance_from_start < smallest_dist
          #     smallest_dist = linker.distance_from_start
          #   end
          # end
          linker = RoutesAndCheckpointsLinker.where(route_id: route.id).order("position_in_route DESC").first
          if linker
            @linker.distance_from_start = linker.distance_from_start + 1
            @linker.position_in_route = linker.position_in_route + 1
          else
            @linker.distance_from_start = 0
            @linker.position_in_route = 0
          end
          #@linker.distance_from_start = smallest_dist - 1
          @linker.route_id = route.id
          #@linker.position_in_route = smallest_pos - 1

          @linker.route_id = route.id
          @linker.advised_time = 0
          @linker.save
          new_linkers.push(@linker.id)
        end
      end
      session[:new_linkers] = new_linkers
      #finds the next linker and redirects to it or goes to index
      if @route_ids
        @route_id = session[:linker_route_ids].at(session[:linker_route_ids_index])
        @route = RoutesAndCheckpointsLinker.where(checkpoint_id: session[:linker_check_id], route_id: @route_id).first
        redirect_to edit_routes_and_checkpoints_linker_path(@route)
      else
        redirect_to checkpoints_path
      end
    else
      render :edit
    end
  end

  # DELETE /checkpoints/1
  def destroy
    @events_routes_and_checkpoints_linkers = RoutesAndCheckpointsLinker.where(checkpoint_id: @checkpoint.id)
    if @events_routes_and_checkpoints_linkers != 0
      @events_routes_and_checkpoints_linkers.each do |linker|
        route = Route.where(id: linker.route_id).first
        linker_pos = linker.position_in_route.dup
        spreadsheet = Spreadsheet.new
        spreadsheet.delete_checkpoint((Route.where(id: linker.route_id).first), @checkpoint.name, linker.position_in_route)
        linker.destroy
        linkers = RoutesAndCheckpointsLinker.where(route_id: route.id)
        linkers.each do |linkerss|
          if linkerss.position_in_route > linker_pos
            linkerss.position_in_route = linkerss.position_in_route - 1
            linkerss.save
          end
        end 
      end
    end
    marshals = Marshall.where(checkpoints_id: @checkpoint.id)
    times = CheckpointTime.where(checkpoint_id: @checkpoint.id)
    times.each do |time|
      time.destroy
    end
    walkers = Participant.where(checkpoints_id: @checkpoint.id)
    walkers.each do |walker|
      linker = RoutesAndCheckpointsLinker.where(route_id: walker.routes_id, position_in_route: 1).first
      walker.update(checkpoints_id: linker.checkpoint_id)
    end
    marshals.each do |marshal|
      marshal.update(checkpoints_id: nil)
    end
    @checkpoint.destroy
    redirect_to checkpoints_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkpoint
      @checkpoint = Checkpoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def checkpoint_params
      params.require(:checkpoint).permit(:name, :os_grid)
    end
end

app/views/checkpoints/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@checkpoint) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :distance
    = f.input :location
    = f.input :advisedTime
    = f.input :description

  .form-actions
    = f.button :submit

app/views/checkpoints/edit.html.haml
.d-flex.justify-content-center
  %h1.fw-bold Edit Checkpoint Info
%br/

= simple_form_for(@checkpoint) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: "Checkpoint Name:"
    = f.input :os_grid, label: "OS Grid Reference:"
    - @routes = Route.where(event_id: session[:current_event_id])
    .row 
      - @routes.each do |route|
        -linker = RoutesAndCheckpointsLinker.where(route_id: route.id, checkpoint_id: @checkpoint.id).first
        -if linker
          .col-6.pb-3
            .card.h-100
              .card-body
                %h5.card-title.fw-bold= route.name
                = check_box_tag 'selected_routes[]', route.id, checked = "checked"
                = "Assign To Route"
        -else
          .col-6.pb-3
            .card.h-100
              .card-body
                %h5.card-title.fw-bold= route.name
                = check_box_tag 'selected_routes[]', route.id
                = "Assign To Route"
        %br/

  %br
  .form-actions
    .d-grid.gap-2
      = f.button :submit, "Save", class: 'btn btn-primary primary-button'
      = link_to 'Delete', @checkpoint, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger danger-button'

app/views/checkpoints/from_file.html.haml
.d-flex.justify-content-center
    %h1.fw-bold Add Checkpoints From Excel

= simple_form_for :upload_excel, url: upload_excel_checkpoints_path, method: :post do |f|

    .form-inputs
        = f.file_field :file, label: "Upload file:"
        - @routes = Route.where(event_id: session[:current_event_id])
        .row 
            - @routes.each do |route|
                .col-6
                    .card.h-100
                        .card-body
                            %h5.card-title.fw-bold= route.name
                            = check_box_tag 'selected_routes[]', route.id
                            /= radio_button :route_id, route.id
                            = "Assign To Route" 
                            /= route.name
                %br/
    %br

    .form-actions
        .d-grid.gap-2
            = f.button :submit, "Upload", class: 'btn btn-primary primary-button w-100'

app/views/checkpoints/index.html.haml
.d-flex.justify-content-center
    %h1.fw-bold.pb-3 Checkpoints

- if session[:new_event] == 0
    //= link_to edit_event_path(@event) do 
    //    %span.bi.bi-arrow-return-left

.row
    - @checkpoints.each do |checkpoint|
        .col-6.pb-3
            .card.h-100
                .card-body
                    %h5.card-title.fw-bold= checkpoint.name
                    %h6= "Location: #{checkpoint.os_grid}"
                    %p.pt-3= link_to 'Edit', edit_checkpoint_path(checkpoint), class: 'btn btn-primary primary-button stretched-link w-100'

.d-flex.justify-content-center
    =link_to "Create New Checkpoint", new_checkpoint_path, class: 'btn btn-primary primary-button w-100'

%br
.d-flex.justify-content-center
    =link_to "Upload Checkpoints", from_file_checkpoints_path, class: 'btn btn-primary primary-button w-100'

- if session[:new_event] == 1
    .d-flex.justify-content-center
    %br
        =link_to "Next", edit_branding_path(@branding), class: 'btn btn-primary primary-button w-100'


    -#     .d-flex.justify-content-left
    -#         %p= checkpoint.name
    -#     .d-flex.justify-content-left
    -#         %p Location:
    -#         %p= checkpoint.os_grid
    -#         %p= link_to 'Edit', edit_checkpoint_path(checkpoint), class: 'btn btn-primary primary-button stretched-link'           
    -#     %br/
    -# .d-flex.justify-content-center
    -#     =link_to "Create New Checkpoint", new_checkpoint_path, class: 'btn btn-primary primary-button'
        

    

            
                

app/views/checkpoints/new.html.haml
.d-flex.justify-content-center
    %h1.fw-bold New Checkpoint

= simple_form_for(@checkpoint) do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

    .form-inputs
        = f.input :name, label: "Checkpoint Name:"
        = f.input :os_grid, label: "OS Grid Reference:"
        - @routes = Route.where(event_id: session[:current_event_id])
        .row 
            - @routes.each do |route|
                .col-6
                    .card.h-100
                        .card-body
                            %h5.card-title.fw-bold= route.name
                            = check_box_tag 'selected_routes[]', route.id
                            = "Assign To Route" 
                            /= route.name
                %br/

    %br
    .form-actions
        .d-grid.gap-2
            = f.button :submit, "Save", class: 'btn btn-primary primary-button'

app/views/checkpoints/show.html.haml
%p#notice= notice


%p
  %b Name:
  = @checkpoint.name
%p
  %b Distance:
  = @checkpoint.distance
%p
  %b Location:
  = @checkpoint.location
%p
  %b Advised Time:
  = @checkpoint.advisedTime
%p
  %b Description:
  = @checkpoint.description

= link_to 'Edit', edit_checkpoint_path(@checkpoint)
\|
= link_to 'Back', checkpoints_path