config/routes.rb
Rails.application.routes.draw do

  resources :calls
  resources :reports
  resources :pickups
  resources :routes
  resources :routes_and_checkpoints_linkers
  resources :checkpoint_times
  resources :brandings
  resources :events do
    post :make_public, on: :collection
    post :make_private, on: :collection
  end
  resources :checkpoints do
    get 'from_file', on: :collection
    post :upload_excel, on: :collection
  end
  #resources :participants
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    get 'pick_route', on: :collection
    post :route_picked, on: :collection
  end
 
  resources :pages do 
    get 'home', on: :member
    get 'pick_event', on: :collection
    get 'pick_route', on: :member
    get 'leaderboard', on: :collection
    get 'single_user_leaderboard', on: :collection
  end

  resources :walkers do
    get 'check_in', on: :collection
    get 'requestCall'
    get 'requestPickUp'
    get 'check_in_fail', on: :collection
    get 'checkpoint_info', on: :collection
    get 'help', on: :collection
    get 'drop_out', on: :collection
    get 'search', on: :collection
    post 'saveLocation'
    get 'sign_up_participant'
    post :make_own_way_home, on: :collection
  end

  resources :admins do
    get 'pick_route', on: :collection
    get 'view_marshals', on: :collection
    get 'view_walkers', on: :collection
    get 'view_pickups', on: :collection
    get 'walkers_profile', on: :collection
    get 'view_calls', on: :collection
    post :make_walker_marshal, on: :collection
    post :make_user_admin, on: :collection
    post :choose_a_route, on: :collection
    get 'checkpoint_order', on: :collection
    get 'view_reports', on: :collection
    post :route_picked, on: :collection
  end

  resources :marshals do
    get 'choose_event', on: :collection
    get 'add_shift', on: :member
    get 'view_incoming_walkers', on: :collection
    get 'change_checkpoint', on: :collection
    post :search_checkpoint, on: :collection
    get 'end_marshal_shift', on: :collection
    get 'end_for_the_day', on: :collection
    get 'checkin_walkers', on: :collection
    post :checkin_walker, on: :collection
    
    get 'move_own_way_home', on: :collection
    get 'request_pick_up', on: :collection
    get 'pause_marshalling', on: :collection
    get 'resume_marshalling', on: :collection
    
    end

  resources :profile do
    get 'account', on: :collection
  end
  
  mount EpiCas::Engine, at: "/"
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get '/marshals/:id', to: 'marshals#index'
  get '/walkers/:id', to: 'walkers#index'


  root :to => redirect("/users/sign_in")
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/marshals_controller.rb
class MarshalsController < ApplicationController
    before_action :authenticate_user!
    
    before_action do
        user = User.where(id: session[:current_user_id]).first
        tag = Tag.where(id: user.tag_id).first
        if tag.name == "Marshal"
        elsif tag.name == "Admin"
            redirect_to events_path, notice: 'You dont have access to that page'
        elsif tag.name == "Walker"
            redirect_to pick_event_pages_path, notice: 'You dont have access to that page'
        end
    end

    def choose_event
        @marshal = Marshall.where(user_id: current_user.id).first
        @marshal_shift = MarshalShift.where(marshalls_id: @marshal.id).first
        @checkpoint = @marshal.checkpoints_id
        if @marshal_shift == nil
            @marshal_shift = MarshalShift.create(current_time: Time.now , status:"Finished", marshalls_id:@marshal.id)
        end

        if @marshal_shift.status == 'Finished' || @marshal.checkpoints_id == nil
           @events = Event.where(made_public: true)
        else
            @checkpoint = @marshal.checkpoints_id
            if @marshal.checkpoints_id == nil
                @events = Event.where(made_public: true)
                MarshalShift.create(current_time: Time.now , status:"Finished", marshalls_id:@marshal.id)
            else
                redirect_to marshal_path(@checkpoint)
            end 
        end 
    end

    def add_shift
        @marshal = Marshall.where(user_id: current_user.id).first
        session[:current_event_id] = params[:id]
        @checkpoints = Checkpoint.where(event_id: params[:id])
        @marshal_shift = MarshalShift.where(marshalls_id: @marshal.id).first
        if @marshal_shift.status 
            @marshal_shift.update(status:"Started")
        end

        # else
        #     MarshalShift.create(current_time: Time.now , status:"Started", marshalls_id:@marshal.id)
        # end
    end
    
    #GET
    def change_checkpoint
        @marshal = Marshall.where(user_id: current_user.id).first
        @checkpoints = Checkpoint.where(event_id: session[:current_event_id])
    end
   
    #POST
    def search_checkpoint
        @marshal = Marshall.where(user_id: current_user.id).first
        @parameter = params[:search][:name].downcase
        @checkpoints = Checkpoint.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
        render :change_checkpoint
    end

    def end_marshal_shift
    end

    def view_incoming_walkers
        user = User.where(id: session[:current_user_id]).first
        marshal = Marshall.where(user_id: user.id).first
        checkpoint = Checkpoint.where(id: marshal.checkpoints_id).first

        linkers = RoutesAndCheckpointsLinker.where(checkpoint_id: checkpoint.id)
        
        @needs_help = Array.new
        @falling_behind = Array.new
        @on_pace = Array.new
        @walkers_need_help = Array.new
        @walkers_falling_behind = Array.new
        @Walkers_on_pace = Array.new
        linkers.each do |linker|
            previous_linker = RoutesAndCheckpointsLinker.where(position_in_route: (linker.position_in_route - 1), route_id: linker.route_id).first
            if previous_linker
                calc_status = Participant.where(routes_id: previous_linker.route_id, checkpoints_id: previous_linker.checkpoint_id)
                calc_status.each do |stat|
                    time_now = Time.now.utc
                    time_last_checkpoint = CheckpointTime.where(participant_id: stat.id, checkpoint_id: previous_linker.checkpoint_id).first.times
                    time_to_next_checkpoint = linker.advised_time
                    dif = time_now - time_last_checkpoint # seconds
                    on_pace = (time_to_next_checkpoint * 60)/dif
                    if on_pace > 1
                        stat.update(pace: "On Pace.")
                    elsif on_pace > 0.65 #if the current pace is 1.54x (ish) bigger than expected, get help
                        stat.update(pace: "Falling Behind!")
                    else
                        stat.update(pace: "Very Far Behind!!")
                    end
                end

                @walkers_need_help.concat Participant.where(routes_id: previous_linker.route_id, pace: 'Very Far Behind!!', checkpoints_id: previous_linker.checkpoint_id)
                @walkers_need_help.each do |walker|
                    @help_walker_and_user = [walker, User.where(id: walker.user_id).first]
                    @needs_help.push(@help_walker_and_user)
                end
                @walkers_falling_behind.concat Participant.where(routes_id: previous_linker.route_id, pace: 'Falling Behind!', checkpoints_id: previous_linker.checkpoint_id)
                @walkers_falling_behind.each do |walker|
                    @falling_walker_and_user = [walker, User.where(id: walker.user_id).first]
                    @falling_behind.push(@falling_walker_and_user)
                end
                @Walkers_on_pace.concat Participant.where(routes_id: previous_linker.route_id, pace: 'On Pace.', checkpoints_id: previous_linker.checkpoint_id)
                @Walkers_on_pace.each do |walker|
                    @on_walker_and_user = [walker, User.where(id: walker.user_id).first]
                    @on_pace.push(@on_walker_and_user)
                end
            end
        end 
    end 

    def show
        session[:current_checkpoint_id] = params[:id]
        user = User.where(id: session[:current_user_id]).first
        @marshal = Marshall.where(user_id: user.id).first
        @marshal.update(checkpoints_id: params[:id])

        @checkpoint = Checkpoint.where(id: @marshal.checkpoints_id).first
        session[:current_event_id] =  @checkpoint.event_id
        linkers = RoutesAndCheckpointsLinker.where(checkpoint_id: @checkpoint.id)
        @num_walkers_passed = 0
        @num_walkers_falling = 0 
        @num_walkers_help = 0

        linkers.each do |linker|
            previous_linker = RoutesAndCheckpointsLinker.where(position_in_route: (linker.position_in_route - 1), route_id: linker.route_id).first
            linkers_after = RoutesAndCheckpointsLinker.where('position_in_route >= ?', linker.position_in_route).where(route_id: linker.route_id)
            linkers_after.each do |linker_after|
                @num_walkers_passed = @num_walkers_passed + Participant.where(routes_id: linker_after.route_id, checkpoints_id: linker_after.checkpoint_id).size
            end
            @num_total_walkers_to_pass = Participant.where(routes_id: linker.route_id).size
            if previous_linker
                @num_walkers_help = @num_walkers_help + Participant.where(routes_id: linker.route_id, pace: 'Very Far Behind!!', checkpoints_id: previous_linker.checkpoint_id).size
                @num_walkers_falling = @num_walkers_falling + Participant.where(routes_id: linker.route_id, pace: 'Falling Behind!', checkpoints_id: previous_linker.checkpoint_id).size
            end
            #there's probably a way to do it in one line for the last 2
        end
    end

    def end_for_the_day

    end
    def  resume_marshalling
        @marshal = Marshall.where(user_id: session[:current_user_id]).first
        @marshal_shift = MarshalShift.where(marshalls_id: @marshal.id).first
        @marshal_shift.update(status:"Started")
        redirect_to marshal_path(session[:current_checkpoint_id]), notice: 'Marshalling Resumed'
    end
    def  pause_marshalling
        @marshal = Marshall.where(user_id: session[:current_user_id]).first
        @marshal_shift = MarshalShift.where(marshalls_id: @marshal.id).first
        @marshal_shift.update(status:"Paused")
        #MarshalShift.create(current_time:DateTime.now() , status:"Paused", marshalls_id:@marshal.id)
        redirect_to marshal_path(session[:current_checkpoint_id]), notice: 'Marshalling Paused'
    end

    def move_own_way_home
        @marshal = Marshall.where(user_id: session[:current_user_id]).first
        @marshal.update(checkpoints_id: nil)
        @marshal_shift = MarshalShift.where(marshalls_id: @marshal.id).first
        @marshal_shift.update(status:"Finished")
        #MarshalShift.create(current_time: Time.now , status:"Finished", marshalls_id:@marshal.id)
        reset_session
        redirect_to '/'
    end

    def request_pick_up
        @marshal = Marshall.where(user_id: session[:current_user_id]).first
        Pickup.create(user_id: session[:current_user_id], event_id:session[:current_event_id], os_grid: session[:osReference])
        @marshal_shift = MarshalShift.where(marshalls_id: @marshal.id).first
        @marshal_shift.update(status:"Finished")
        #MarshalShift.create(current_time: Time.now , status:"Finished", marshalls_id:@marshal.id)
        reset_session
        redirect_to '/', notice: 'Pick up request successful.'
    end

    #GET
    def checkin_walkers
        @marshal = Marshall.where(user_id: session[:current_user_id]).first
        @checkpoint = Checkpoint.where(id: @marshal.checkpoints_id).first
    end

    #POST
    def checkin_walker
        @walker = Participant.where(params.require(:checkin_walker).permit(:participant_id), event_id: session[:current_event_id]).first
        if @walker
            @marshal = Marshall.where(user_id: session[:current_user_id]).first
            @walker.update(checkpoints_id: @marshal.checkpoints_id)

            #create checkpoint time for walker
            time = Time.now
            @checkpoint_time = CheckpointTime.new
            @checkpoint_time.times = time 
            @checkpoint_time.checkpoint_id = @marshal.checkpoints_id
            @checkpoint_time.participant_id = @walker.id
            @checkpoint_time.save

            #rerank the walker
            #gets walkers at that checkpoint same on route 
            walkers_on_route = Participant.where(routes_id: @walker.routes_id, checkpoints_id: @marshal.checkpoints_id)
            lowest_rank = 0

app/views/marshals/add_shift.html.haml
.d-flex.justify-content-center
  %h1.fw-bold Start Your Shift
.d-flex.justify-content-center
  %h4.fw-bold Choose Your Current Checkpoint

- if @checkpoints.count == 0
  %h3 There are no checkpoints ready. Please contact Admin to Generate one.
- else 
  %h3
  .row
    - @checkpoints.each do |checkpoint|
      .col-6.mb-3
        = link_to marshal_path(checkpoint) do
          .card
            .card-body
              %h5.card-title.fw-bold= checkpoint.name
          
  %br/
%br/

 

app/views/marshals/change_checkpoint.html.haml
.d-flex.justify-content-center
  %h1.fw-bold Change Checkpoint

.row 
  .col
    .d-flex.justify-content-center 
    = simple_form_for :search, url: search_checkpoint_marshals_path, method: :post do |f|
      = f.input :name
      = f.submit 'Search', class: "btn btn-primary primary-button btn-sm w-100 mb-2"
      = link_to 'Reset Search', change_checkpoint_marshals_path, class: "btn btn-primary primary-button btn-sm w-100"
%br

.row
  - @checkpoints.each do |checkpoint|
    .col-6.pb-3
      =link_to marshal_path(checkpoint) do
        .card.h-100
          .card-body
            - if checkpoint.id == @marshal.checkpoints_id
              %h5.card-title.fw-bold= checkpoint.name
              %h6.card-title.fw-bold Current Checkpoint
            - else
              %h5.card-title.fw= checkpoint.name
%br/

app/views/marshals/checkin_walkers.html.haml
.row 
    .col
        .d-flex.justify-content-center
            %h3.fw-bold Current Checkpoint: 
        .d-flex.justify-content-center
            %h1.fw-bold.text-uppercase.text-center= @checkpoint.name
        %br
        .d-flex.justify-content-center
            = simple_form_for :checkin_walker, url: checkin_walker_marshals_path, method: :post do |f|
                = f.input :participant_id, label: "Walker Number:"
                %br/
                = f.submit "Checkin Walker", class: 'btn btn-primary primary-button w-100'
        

app/views/marshals/choose_event.html.haml
.d-flex.justify-content-center
  %h1.fw-bold.pb-3 Choose An Event


- if @events.count == 0
  %h3 There is no event ready. Please contact an admin for them to create one.
- else 
  %h3 
  .row
    - @events.each do |event|
      .col-6.pb-3
        =link_to  add_shift_marshal_path(event.id) do
          .card.h-100
            .card-body
              .d-flex.justify-content-center
                %h5.card-title.fw-bold= event.name
            
  %br/
%br/

app/views/marshals/end_for_the_day.html.haml
.row 
    .col
        .d-flex.justify-content-center
            %h1.fw-bold.text-center End Marshal Shift For The Day
        %br
        .d-flex.justify-content-center
            %h5.text-center Thank you for all your help today!
        %br/
        .d-flex.justify-content-center
            %p.text-center Now that you're wrapped up, do you need picking up, or are you making your own way home?
        %br/

.d-grid.gap-2
    // needs functionality
    =link_to "Making My Own Way Home", move_own_way_home_marshals_path,class: 'btn btn-primary primary-button'
    =link_to "I Need Picking Up", request_pick_up_marshals_path, class: 'btn btn-primary primary-button'

app/views/marshals/end_marshal_shift.html.haml
.row 
    .col
        .d-flex.justify-content-center
            %h1.fw-bold End Marshal Shift
        %br
        .d-flex.justify-content-center
            %h5 Thank you for all your help today!
        %br/
        .d-flex.justify-content-center
            %p.text-center Would you like to pause your shift or clock out permanently for the day?
        %br/

.d-grid.gap-2
    =link_to "Pause Marshalling", pause_marshalling_marshals_path, class: 'btn btn-primary primary-button'
    =link_to "End For The Day", end_for_the_day_marshals_path, class: 'btn btn-primary primary-button'

app/views/marshals/index.html.haml
.row 
    .col 
        .d-flex.justify-content-center
            %h3.fw-bold Current Checkpoint: 
        .d-flex.justify-content-center
            %h1.text-center.fw-bold.text-uppercase= @checkpoint.name
        %br
        .d-flex.justify-content-center
            %h3.fw-bold Walkers Passed:
        .d-flex.justify-content-center
            %h1.fw-bold= (@num_walkers_passed).to_s + ' of ' + ('Placeholder').to_s
        %br
        .d-flex.justify-content-center 
            %h3.fw-bold Walkers Falling Behind:
        .d-flex.justify-content-center
            %h1.fw-bold= @num_walkers_falling

%br
.d-grid.gap-2
    =link_to "View Incoming Walkers", view_incoming_walkers_marshals_path, class: 'btn btn-primary primary-button'
    =link_to "Change Checkpoint", change_checkpoint_marshals_path, class: 'btn btn-primary primary-button'
    =link_to "Checkin Walkers", checkin_walkers_marshals_path, class: 'btn btn-primary primary-button'
    =link_to "End Marshal Shift", end_marshal_shift_marshals_path, class: 'btn btn-primary primary-button'
%br
%table.table.table-hover.table-sm
    %thead
        %tbody
            %tr
                %td= 'Marshal ID: ' + (@marshal.marshal_id).to_s

app/views/marshals/show.html.haml
- @marshal_shift = MarshalShift.where(marshalls_id: @marshal.id).first
- if @marshal_shift.status == "Started"
    .row 
        .col 
            .d-flex.justify-content-center
                %h3.fw-bold Current Checkpoint: 
            .d-flex.justify-content-center
                -if @checkpoint == nil
                    %h1.text-center.fw-bold.text-uppercase No Checkpoint
                -else
                    %h1.text-center.fw-bold.text-uppercase= @checkpoint.name
            %br

            .d-flex.justify-content-center
                %h4.fw-bold Walkers Passed:
            .d-flex.justify-content-center
                %h2.fw-bold= "#{@num_walkers_passed} of #{@num_total_walkers_to_pass}"
            %br
            .d-flex.justify-content-center 
                %h4.fw-bold Walkers Falling Behind:
            .d-flex.justify-content-center
                %h2.fw-bold= (@num_walkers_help+@num_walkers_falling).to_s
            %br

    .d-grid.gap-2 
        =link_to "View Incoming Walkers", view_incoming_walkers_marshals_path, class: 'btn btn-primary primary-button'
        =link_to "Change Checkpoint", change_checkpoint_marshals_path, class: 'btn btn-primary primary-button'
        =link_to "Checkin Walkers", checkin_walkers_marshals_path, class: 'btn btn-primary primary-button'
        =link_to "End Marshal Shift", end_marshal_shift_marshals_path, class: 'btn btn-primary primary-button'
    %br

- elsif @marshal_shift.status == "Paused"
    .row 
        .col 
            .d-flex.justify-content-center
                %h3.fw-bold Current Checkpoint: 
            .d-flex.justify-content-center
                %h1.text-center.fw-bold.text-uppercase= "Shift " + @marshal_shift.status
            %br

            .d-flex.justify-content-center
                %h4.fw-bold.text-muted Walkers Passed:
            .d-flex.justify-content-center
                %h2.fw-bold.text-muted=  "Shift " + @marshal_shift.status
            %br
            .d-flex.justify-content-center 
                %h4.fw-bold.text-muted Walkers Falling Behind:
            .d-flex.justify-content-center
                %h2.fw-bold.text-muted=  "Shift " + @marshal_shift.status
            %br

    .d-grid.gap-2
        =link_to "View Incoming Walkers", view_incoming_walkers_marshals_path, class: 'btn btn-primary primary-button disabled'
        =link_to "Change Checkpoint", change_checkpoint_marshals_path, class: 'btn btn-primary primary-button disabled'
        =link_to "Checkin Walkers", checkin_walkers_marshals_path, class: 'btn btn-primary primary-button disabled'
        =link_to "Resume Marshal Shift", resume_marshalling_marshals_path, class: 'btn btn-primary primary-button'
    %br


%table.table.table-hover.table-sm
    %thead
        %tbody
            %tr
                %td= 'Marshal ID: ' + (@marshal.marshal_id).to_s
            %tr
                %td= 'Status: ' + @marshal_shift.status

app/views/marshals/view_incoming_walkers.html.haml
.d-flex.justify-content-center
    %h1.fw-bold Incoming Walkers

.d-flex.justify-content-center
    -if @needs_help.count == 1
        %p.fw-bold= "There is a walker very far behind." 
    -else
        %p.fw-bold= "There are #{@needs_help.count} walkers very far behind."

.d-flex.justify-content-center
    %table.black-line
        %tbody
            %tr
                %td.fw-bold ID Number
                %td.fw-bold Person
                %td.fw-bold Pace
            -if @needs_help
                -@needs_help.each do |walker|
                    %tr 
                        %td= walker.first.participant_id
                        %td=link_to "#{walker.last.name}", walker.last
                        %td.need-help Very Far Behind!!

            -if @falling_behind
                -@falling_behind.each do |walker|
                    %tr 
                        %td= walker.first.participant_id
                        %td=link_to "#{walker.last.name}", walker.last
                        %td.falling-behind Falling Behind!
                        
            -if @on_pace
                -@on_pace.each do |walker|
                    %tr
                        %td= walker.first.participant_id
                        %td=link_to "#{walker.last.name}", walker.last
                        %td.on-pace On Pace