config/routes.rb
Rails.application.routes.draw do

  resources :calls
  resources :reports
  resources :pickups
  resources :routes
  resources :routes_and_checkpoints_linkers
  resources :checkpoint_times
  resources :brandings
  resources :events do
    post :make_public, on: :collection
    post :make_private, on: :collection
  end
  resources :checkpoints do
    get 'from_file', on: :collection
    post :upload_excel, on: :collection
  end
  #resources :participants
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    get 'pick_route', on: :collection
    post :route_picked, on: :collection
  end
 
  resources :pages do 
    get 'home', on: :member
    get 'pick_event', on: :collection
    get 'pick_route', on: :member
    get 'leaderboard', on: :collection
    get 'single_user_leaderboard', on: :collection
  end

  resources :walkers do
    get 'check_in', on: :collection
    get 'requestCall'
    get 'requestPickUp'
    get 'check_in_fail', on: :collection
    get 'checkpoint_info', on: :collection
    get 'help', on: :collection
    get 'drop_out', on: :collection
    get 'search', on: :collection
    post 'saveLocation'
    get 'sign_up_participant'
    post :make_own_way_home, on: :collection
  end

  resources :admins do
    get 'pick_route', on: :collection
    get 'view_marshals', on: :collection
    get 'view_walkers', on: :collection
    get 'view_pickups', on: :collection
    get 'walkers_profile', on: :collection
    get 'view_calls', on: :collection
    post :make_walker_marshal, on: :collection
    post :make_user_admin, on: :collection
    post :choose_a_route, on: :collection
    get 'checkpoint_order', on: :collection
    get 'view_reports', on: :collection
    post :route_picked, on: :collection
  end

  resources :marshals do
    get 'choose_event', on: :collection
    get 'add_shift', on: :member
    get 'view_incoming_walkers', on: :collection
    get 'change_checkpoint', on: :collection
    post :search_checkpoint, on: :collection
    get 'end_marshal_shift', on: :collection
    get 'end_for_the_day', on: :collection
    get 'checkin_walkers', on: :collection
    post :checkin_walker, on: :collection
    
    get 'move_own_way_home', on: :collection
    get 'request_pick_up', on: :collection
    get 'pause_marshalling', on: :collection
    get 'resume_marshalling', on: :collection
    
    end

  resources :profile do
    get 'account', on: :collection
  end
  
  mount EpiCas::Engine, at: "/"
  match "/403", to: "errors#error_403", via: :all
  match "/404", to: "errors#error_404", via: :all
  match "/422", to: "errors#error_422", via: :all
  match "/500", to: "errors#error_500", via: :all

  get :ie_warning, to: 'errors#ie_warning'
  get '/marshals/:id', to: 'marshals#index'
  get '/walkers/:id', to: 'walkers#index'


  root :to => redirect("/users/sign_in")
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id           :bigint           not null, primary key
#  made_public  :boolean
#  name         :string
#  phone_number :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Event < ApplicationRecord
    validates_presence_of :name
    validates_uniqueness_of :name

    validates :phone_number,  presence:{message: 'Can Not Be Blank!'},
                      numericality: true,
                      length:{minimum: 11, maximum:15}


    has_many :calls, dependent: :destroy
    has_one :branding, dependent: :destroy                 
    has_many :checkpoints, dependent: :destroy
    has_many :routes, dependent: :destroy
    
    has_many :participants


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action do
    user = User.where(id: session[:current_user_id]).first
    tag = Tag.where(id: user.tag_id).first
    if tag.name == "Admin"
    elsif tag.name == "Marshal"
      redirect_to pick_event_pages_path, notice: 'You dont have access to that page'
    elsif tag.name == "Walker"
      redirect_to pick_event_pages_path, notice: 'You dont have access to that page'
    end
  end

  # GET /events
  def index
    @events = Event.all
    @walker = User.ransack(params[:q])
    session.delete(:current_event_id)
  end

  # GET /events/1
  def show
    session[:new_event] = 0
    session[:current_event_id] = @event.id
    @enough_checkpoints = 1
    routes = Route.where(event_id: session[:current_event_id])
    if !(routes.first)
      @enough_checkpoints = 0
    end
    routes.each do |route|
      if RoutesAndCheckpointsLinker.where(route_id: route.id).size == 0
        @enough_checkpoints = 0
      end
    end
    
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    session[:new_event] = 0
  end

  # POST /events
  def create
    @event = Event.new(event_params)
    @event.made_public = false
    if @event.save
      session[:current_event_id] = @event.id
      session[:new_event] = 1
      @branding = Branding.new
      @branding.event_id = session[:current_event_id]
      @branding.save
      redirect_to routes_path
    else 
      render :new
    end
  end

  def make_public
    event = Event.where(params.require(:make_public).permit(:id)).first
    event.update(made_public: true)
    redirect_to event
  end

  def make_private
    event = Event.where(params.require(:make_private).permit(:id)).first
    event.update(made_public: false)
    redirect_to event
  end

  # PATCH/PUT /events/1
  def update
    old_name = @event.name.dup
    if @event.update(event_params)
      spreadsheet = Spreadsheet.new
      spreadsheet.update_event(old_name, @event)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    #delete the routes and the routes and checkpoints linkers
    @events_routes = Route.where(event_id: @event.id)
    if @events_routes != 0
      @events_routes.each do |route|
        @events_routes_and_checkpoints_linkers = RoutesAndCheckpointsLinker.where(route_id: route.id)
        if @events_routes_and_checkpoints_linkers != 0
          @events_routes_and_checkpoints_linkers.each do |linker|
            linker.destroy
          end
        end
        walkers = Participant.where(routes_id: route.id)
        walkers.each do |walker|
          times = CheckpointTime.where(participant_id: walker.id)
          times.each do |time|
            time.destroy
          end
          walker.destroy
        end
        spreadsheet = Spreadsheet.new
        spreadsheet.delete_event(@event)
        route.destroy
      end
    end
    #delete the checkpoints
    @events_checkpoints = Checkpoint.where(event_id: @event.id)
    if @events_checkpoints != 0
      @events_checkpoints.each do |checkpoint|
        marshals = Marshall.where(checkpoints_id: checkpoint.id)
        marshals.each do |marshal|
          marshal.update(checkpoints_id: nil)
        end
        checkpoint.destroy
      end
    end
    #delete the branding
    @events_branding = Branding.where(event_id: @event.id)
    if @events_branding != 0
      @events_branding.each do |branding|
        branding.destroy
      end
    end
    @event.destroy
    redirect_to events_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :phone_number)
    end
end

app/views/events/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@event) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :phone_number

  .form-actions
    = f.button :submit

app/views/events/edit.html.haml
.d-flex.justify-content-center
  %h1.fw-bold Edit Event Info

= simple_form_for(@event) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: "Event Name:"
    = f.input :phone_number, label: "Head Marshal Phone Number:"

  .form-actions
    .d-grid.gap-2
      = f.button :submit, "Save", class: 'btn btn-primary primary-button w-100'
      = link_to 'Delete', @event, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger danger-button w-100 mb-2'
  %br
  .d-grid.gap-2
    =link_to "Manage Routes", routes_path, class: 'btn btn-primary primary-button w-100'
  
    =link_to "Manage Checkpoints", checkpoints_path, class: 'btn btn-primary primary-button w-100'

    =link_to "View Checkpoints Order", checkpoint_order_admins_path, class: 'btn btn-primary primary-button w-100'

    =link_to "Manage Branding", edit_branding_path(Branding.where(event_id: session[:current_event_id]).first), class: 'btn btn-primary primary-button w-100'
  

  

app/views/events/index.html.haml
.d-flex.justify-content-center
  %h1.fw-bold.pb-3 Your Events

.row 
  - @events.each do |event|
    .col-6.pb-3
      =link_to event do
        .card.h-100
          .card-body
            %h5.card-title.fw-bold= event.name
          

.d-flex.justify-content-center
  =link_to "Create New Event", new_event_path, class: 'btn btn-primary primary-button w-100'
%br
.d-flex.justify-content-center
  =link_to "View Reported Issues With Site", view_reports_admins_path, class: 'btn btn-primary primary-button w-100'

app/views/events/new.html.haml
.d-flex.justify-content-center
  %h1.fw-bold Create Event
%br

= simple_form_for(@event) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: "Event Name:"
    = f.input :phone_number, label: "Head Marshal Phone Number:"
  %br
  
  .form-actions
    = f.button :submit, "Create", class: 'btn btn-primary primary-button w-100'

app/views/events/show.html.haml
.d-flex.justify-content-center
  %h1.fw-bold= @event.name
%br

.d-grid.gap-2
  =link_to "View Participants", view_walkers_admins_path, class: 'btn btn-primary primary-button btn-lg'
  =link_to "View Marshals", view_marshals_admins_path, class: 'btn btn-primary primary-button btn-lg'
  =link_to "View Event Leaderboard", pick_route_admins_path, class: 'btn btn-primary primary-button btn-lg'
  =link_to "View Pick-Up Requests", view_pickups_admins_path, class: 'btn btn-primary primary-button btn-lg'
  =link_to "View Phone Call Requests", view_calls_admins_path, class: 'btn btn-primary primary-button btn-lg'
  %br
  =link_to "Event Info", edit_event_path(@event), class: 'btn btn-primary primary-button'
  -if @enough_checkpoints == 0
    .d-grid.gap-2
      = button_tag "To Make Event Public All Routes Need A Checkpoint", class: 'btn btn-primary primary-button'
  -elsif @event.made_public && @enough_checkpoints == 1
    = simple_form_for :make_private, url: make_private_events_path, method: :post do |f|
      = f.hidden_field :id, value: @event.id
      .d-grid.gap-2
        = f.submit "Make Event Private", :data => { :confirm => 'Are you sure?' }, class: 'btn btn-primary primary-button'
  -else
    = simple_form_for :make_public, url: make_public_events_path, method: :post do |f|
      = f.hidden_field :id, value: @event.id
      .d-grid.gap-2
        = f.submit "Make Event Public", :data => { :confirm => 'Are you sure?' }, class: 'btn btn-primary primary-button'    
  =link_to "Switch Event", events_path, class: 'btn btn-primary primary-button'